'use strict'

// Build-time compilation: a valibot schema becomes a standalone JavaScript
// module that imports nothing, not even this package or ata.
//
//   const { compileToModule } = require('@ata-project/valibot/build')
//   fs.writeFileSync('validate-user.js', compileToModule(userSchema))
//
// The emitted module is a plain function. Nothing about valibot or the ata
// engine ships with it, which is the point: the runtime bridge carries a
// general engine that can validate any schema handed to it, while this
// carries only the code for the one schema you compiled.
//
// Only schemas the classifier calls exact (`engine: 'ata'`) can be compiled.
// A hybrid schema is one whose JSON Schema conversion is deliberately looser
// than valibot, with valibot confirming the acceptances at runtime; emitting
// a standalone module for it would drop those checks silently and accept
// documents valibot rejects. This refuses instead. Declining to compile is
// recoverable; a validator that wrongly accepts is not.

const { analyze, toJSONSchema } = require('./index.js')

// The emitter builds the module source through the code generator, so this
// runs at build time in Node. What it emits is plain code with no generation
// of its own, so the compiled module runs anywhere, CSP included.
function codegenAvailable () {
  try {
    // eslint-disable-next-line no-new-func
    new Function('return 1')
    return true
  } catch {
    return false
  }
}

class NotExactError extends Error {
  constructor (analysis) {
    super(
      'this schema cannot be compiled ahead of time: ' + analysis.reasons.join(', ') +
      '. Those features are checked by valibot at runtime, so a standalone module ' +
      'would accept documents valibot rejects. Use compile() from the package root instead.',
    )
    this.name = 'NotExactError'
    this.mode = analysis.mode
    this.reasons = analysis.reasons
  }
}

function header () {
  return '// Generated by @ata-project/valibot from a valibot schema.\n' +
    '// Standalone: imports nothing, including valibot and ata.\n' +
    '//\n' +
    '// This follows JSON Schema semantics, which is what the wire carries.\n' +
    '// One documented difference from valibot in this direction: valibot\'s\n' +
    '// number() accepts Infinity, a value JSON cannot express, and this\n' +
    '// rejects it. Any document that arrived as JSON behaves identically.\n' +
    '//\n' + '// Exports: isValid(data) and validate(data).\n'
}

// Compile a valibot schema to standalone module source.
//
// opts.format: 'esm' (default) or 'cjs'
//
// The module exports `isValid(data)` for the verdict and `validate(data)` for
// the verdict with an error report. Rename at the import site if you are
// compiling several schemas into one place; this deliberately does not
// rewrite the generated source to rename them, because rewriting emitted
// code is how validators start silently accepting things.
function compileToModule (schema, opts) {
  const options = opts || {}
  const analysis = analyze(schema)
  if (analysis.mode !== 'ata') throw new NotExactError(analysis)

  const { Validator } = require('ata-validator')
  const { toStandaloneModule } = require('ata-validator/aot')
  const jsonSchema = toJSONSchema(schema)
  const validator = new Validator(jsonSchema, { assertFormat: false })
  const src = toStandaloneModule(validator, { format: options.format || 'esm' })
  if (!src) {
    throw new Error(
      codegenAvailable()
        ? 'the ata engine declined to emit a standalone module for this schema. ' +
          'Use compile() from the package root instead.'
        : 'compiling to a module needs code generation, which this runtime blocks. ' +
          'Run the compile step at build time in Node; the module it emits is plain ' +
          'code and runs anywhere, including under a strict CSP.',
    )
  }
  return header() + src
}

// Whether a schema can be compiled ahead of time, and why not when it cannot.
function canCompile (schema) {
  const analysis = analyze(schema)
  return {
    ok: analysis.mode === 'ata',
    mode: analysis.mode,
    reasons: analysis.reasons,
  }
}

module.exports = { compileToModule, canCompile, codegenAvailable, NotExactError }
